"""New column Video table

Revision ID: 199ea6f6ee8c
Revises: 30ff78bb96d8
Create Date: 2023-12-02 03:24:53.199963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199ea6f6ee8c'
down_revision: Union[str, None] = '30ff78bb96d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'status')
    # ### end Alembic commands ###
