"""update user table

Revision ID: 5bfa1dd9ce16
Revises: 199ea6f6ee8c
Create Date: 2023-12-18 03:26:29.412136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfa1dd9ce16'
down_revision: Union[str, None] = '199ea6f6ee8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_social_user', sa.Boolean(), server_default=sa.text('False'), nullable=True))
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_social_user')
    # ### end Alembic commands ###
