"""Add blob id column

Revision ID: 80f5b5c8875b
Revises: bc7fa1bfe728
Create Date: 2023-11-17 01:13:40.613499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f5b5c8875b'
down_revision: Union[str, None] = 'bc7fa1bfe728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('blob_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'blob_id')
    # ### end Alembic commands ###
