"""Add title column

Revision ID: bc7fa1bfe728
Revises: f567d3c913f9
Create Date: 2023-11-17 00:57:06.711007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7fa1bfe728'
down_revision: Union[str, None] = 'f567d3c913f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title', sa.String(), nullable=False, server_default=" "))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'title')
    # ### end Alembic commands ###
