"""Your migration message here

Revision ID: d17c55f495ea
Revises: 5bfa1dd9ce16
Create Date: 2023-12-24 04:35:17.105241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17c55f495ea'
down_revision: Union[str, None] = '5bfa1dd9ce16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
