"""update video table

Revision ID: f567d3c913f9
Revises: 439fcd5b89fa
Create Date: 2023-11-17 00:24:15.700804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f567d3c913f9'
down_revision: Union[str, None] = '439fcd5b89fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_url', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(), nullable=False))
    op.drop_column('videos', 'blob_id')
    op.drop_column('videos', 'video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('blob_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 'video_url')
    # ### end Alembic commands ###
